### ISSUE TITLE
cscript build.wsf /msi error

### ISSUE THREAD

**Issue by zxw1104** [OpenVPN/openvpn-build#184]
cscript build.wsf /msi 
Microsoft JScript 运行时错误: WiX compiler returned non-zero.
Thanks

**Comment by selvanair** [comment]
If you still have this "runtime error" from WiX, you will have to give more details so that someone may be able to help. Is that only output printed, what version of WiX and Windows etc may give some clue.

BTW, I think the argument should be msi, not /msi though that shouldn't cause any error -- the builder will just ignore it and do the default msi + exe build.

**Comment by zxw1104** [comment]
The problem has been solved，Thanks!
