### ISSUE TITLE
OpenVPN 2.5-beta2 MSI installer does not update files whose version does not change

### ISSUE THREAD

**Issue by mattock** [OpenVPN/openvpn-build#188]
Today when testing the [OpenVPN 2.5-beta2 installer](https://build.openvpn.net/downloads/releases/OpenVPN-2.5-beta2-I601-amd64.msi) @lstipakov and I noticed that when installing on top of beta1 some of the files under the "bin" folder do not get updated. Like becm on IRC noted MSI requires updating file versions in all of the files, see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3676 for example.

We can probably fix openvpn.exe by simply incrementing the probably relevant parameter in version.m4:
``` 
define([PRODUCT_VERSION_RESOURCE], [2,5,0,0])
```

However, we cannot do the same for other libraries like pkcs11-helper, lzo or openssl. So we need to keep track of the current versions in openvpn-build/generic/build.vars and increment those on every release _if_ we change then, compile them with different build flags, etc. That way the MSI installer _should_ upgrade the file is they change.

This needs to be fixed before OpenVPN 2.5-beta2 Windows installers are officially released.

**Comment by cron2** [comment]
this is actually a somewhat tough issue, as we want this to reflect the actual openvpn version number on release (so, 2.5.0 would be "2,5,0,<something>") but what about betas...

Will it install a new version if the version is *different*, or only if it is *newer*?

**Comment by cron2** [comment]
If it needs to be "newer", betas could be something like 2,4,9990,601  ("more new than any 2.4.x release, and younger than 2.5.0").

**Comment by becm** [comment]
To replace a versioned file, it has to be higher (see [versioning rules](https://docs.microsoft.com/en-us/windows/win32/msi/file-versioning-rules).

If we do not want to break logic for `openvpn-gui.exe`, next beta would have to be at use version `11.17.0.1`.
LZO is unversioned, new versioned file takes precedence.
OpenSSL libraries currently have respective release versions, cleanup not a problem (`1.1.1.6`→`2.x.y.z`).

To clean this up **now** and move back to `2.4.x.y` (last chance?):
- files from NSIS-installations must be remove during install
- MSI/beta versions have to be cleanly removed before installing newer MSIs.

**Comment by becm** [comment]
Making 3rd party libraries (`LZO`, `OpenSSL`, `pkcs11-helper`) [companion files](https://docs.microsoft.com/en-us/windows/win32/msi/companion-files) to e.g. `openvpn.exe` might reduce complexity but in turn require increasing `openvpn.exe` file version for shipping an `OpenSSL` bugfix update.

**Comment by cron2** [comment]
Hi,

On Sat, Aug 29, 2020 at 08:20:11AM -0700, Marc Becker wrote:
> Making 3rd party libraries (`LZO`, `OpenSSL`, `pkcs11-helper`) [companion files](https://docs.microsoft.com/en-us/windows/win32/msi/companion-files) to e.g. `openvpn.exe` might reduce complexity but in turn require increasing `openvpn.exe` file version for shipping an `OpenSSL` bugfix update.

This is not unreasonable.  We already increase the installer version 
("I601->I602") when we release an OpenSSL bugfix update, and that version 
could be reflected into the OpenVPN file version.

(So, yes, it would replace an openvpn.exe with an identical version, 
but that way we can be sure "all binaries are coming from *this* .msi")

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by becm** [comment]
For proper binary→MSI, file version would move backwards on `openvpn-gui.exe` (`11.17.0.0` → `2.5.0.r_msi`) and TAP driver in MSM (`9.24.4.r_tap` → `2.5.0.r_msi`). Not shure how this would affect driver signing or update.

So maybe only synchronize *openvpn.exe and dependencies* and leave GUI and driver as is.

**Comment by cron2** [comment]
Hi,

On Sun, Aug 30, 2020 at 07:33:42AM -0700, Marc Becker wrote:
> So maybe only synchronize *openvpn.exe and dependencies* and leave GUI and driver as is.

I would not mess with version number for anything that already has a 
proper version number - openssl, tap driver, gui.  If at all, add a build 
number to differenciate rebuilds.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by lstipakov** [comment]
So, what do we do? Here is list of files and versions in `bin` directory. The ones in bold are those which we have problems.

| file name  | version  | 
|---|---|
| libcrypto-1_1-x64.dll  | 1.1.1.7 |
| liblzo2-2.dll  | <empty> |
| **libpkcs11-helper-1.dll**   | 1.0.0.0 |
| libssl-1_1-x64.dll  | 1.1.1.7 |
| openvpn-gui.exe | 1.17.0.0 |
| **openvpn.exe**  | 2.5.0.0 |
| **openvpnserv.exe**  | 2.5.0.0 |
| **tapctl.exe**  | 2.5.0.0 |

* libssl/libcrypto have their own versioning so I think it is ok for them not to be replaced, if versions haven't changed.
* liblzo lacks version information and got replaced. We could leave it as it is, since compression is anyway a dying breed in VPN. 
* libpkcs11-helper needs version increment.
* openvpn binaries also need version increment.

What if:
* we mark libpkcs11 as a "companion" to get it always replaced
* we increment 2.5.0.X -> 2.5.0.X+1 for every release until "2.5.0 stable", then "2.5.0.0" -> "2.5.1.0" and so on
* the rest of files will be automatically replaced if needed according to their versions

**Comment by mattock** [comment]
We discussed this with @lstipakov on #openvpn-devel. The pragmatic approach would be to do what @lstipakov suggests and mark libpkcs11-helper as a "companion" for openvpn.exe. That way if openvpn.exe gets updated libpkcs11-helper gets updated as well.

This is not a perfect solution as in theory we might want to make Windows _installer-only_ releases that update files that follow the OpenVPN versioning scheme (e.g. 2.5.0.0):
* openvpnserv2.exe
* tapctl.exe

**Comment by lstipakov** [comment]
- tapctl is a part of openvpn repo which takes its version from version.m4
- openvpnserv2 is a separate project and has its own versioning system, so update should work just fine

**Comment by becm** [comment]
The distributed DLLs (`libcrypto-1_1-x64.dll`, `liblzo2-2.dll`, `libpkcs11-helper-1.dll` and `libssl-1_1-x64.dll`) are built in sync with and only to be used by `openvpn.exe`.
To better represent this tight relation, it might be more consistent (albeit not necessary for the *current* problem) to make **all** of them companion files to `openvpn.exe`.

Unexpected version changes/retentions due to problems discoverd during a *beta* cycle (e.g. recompile, revert `OpenSSL` from `1.1.2` to `1.1.1`) might arise. If the *companion* states are set consistently now, they will not be have to kept in mind when such an issue arises.

Or as a variation of @cron2's statement for this approach;
"all ~binaries~ `openvpn.exe`-Components are coming from ~*this* .msi~ the *same* build process", *unless someone forgets to adjust version.m4* :).

**Comment by lstipakov** [comment]
After more discussions on #openvpn-devel we decided to use `REINSTALLMODE` MSI property (https://docs.microsoft.com/en-us/windows/win32/msi/reinstallmode) which, when set to ``amus``, makes installer overwrite all files regardless of versions.

**Comment by mattock** [comment]
I believe this problem has now been resolved. Correct @lstipakov?

**Comment by mattock** [comment]
Closing this one, please reopen if the problem still persists.
