### ISSUE TITLE
Wintun latest version

### ISSUE THREAD

**Issue by yukwar** [OpenVPN/openvpn-build#206]
Hello, I would like to know if it is in your plans to update the Wintun.dll library since the version that you use Wintun is version 0.8 as reflected here https: // staging.openvpn.net/openvpn2/. The latest version of Wintun is 10.2, which fixes some bugs and improves performance, we hope to have this latest version. Thanks a lot

**Comment by cron2** [comment]
As of today, we have no plans of changing our code to use wintun.dll - we can not ship a binary 3rd party library (this would be insecure), and we do not currently want to spend time on integrating the wintun.dll build into our build system (if that license even permits us doing so).

Also, since this not just "upgrade a library" but also "change our code to the new API, using wintun.dll instead of the driver API", we can't do that in the middle of the 2.5.x series.

We do plan to release 2.6 in summer this year which will solve this all in very nice ways.

**Comment by qazhub** [comment]
Is there any road-map for changing the code to use `wintun.dll` instead of the driver API?

**Comment by lstipakov** [comment]
Not at the moment. We suggest to switch to [dco](https://openvpn.net/blog/openvpn-data-channel-offload/), which is now in openvpn master branch and will be part of upcoming 2.6 release. You can download the installer [here](https://build.openvpn.net/downloads/snapshots/github-actions/openvpn2/openvpn-master-20220825T0959-104e4ef1-amd64.msi). Note that this is not official release yet and might contain bugs.

**Comment by cron2** [comment]
Hi,

On Thu, Aug 25, 2022 at 06:49:45PM -0700, qazhub wrote:
> Is there any road-map for changing the code to use `wintun.dll` instead of the driver API?

We have no plans to add support for using a binary-only third-party
dll for wintun communication.  The existing driver API works well enough
for us.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
