### ISSUE TITLE
building snapshots in release/2.3 branch

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#30]
@mattock , I'm going to make a PR for release/2.3
that branch is for WinXP builds, right ? so, we need build-complete here, but not build-snapshot ?

**Comment by chipitsine** [comment]
if we are not going to use build-snapshot, so it makes sense to delete the file itself instead of removing "--disable-snappy"

**Comment by mattock** [comment]
The release/2.3 branch in openvpn-build is for doing OpenVPN 2.3.x builds, not just for Windows XP builds.

While build-snapshot is typically used to produce Git "master" builds, I think it can be used to do builds based on the latest commit in "release/2.3" branch of openvpn. If that does not work, I would rather attempt to fix build-snapshot in "release/2.3" branch of openvpn-build rather than delete the file altogether.

**Comment by flichtenheld** [comment]
obsolete
