### ISSUE TITLE
building snapshots is broken

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#39]
when I run ./build-snapshot

```
make[1]: Leaving directory '/home/ilia/temp/openvpn-build/windows-nsis/tmp/build-i686/pkcs11-helper-1.11'
tap-windows
Fixup libtool files
Restore libtool files
Fixup libtool files
Build openvpn
../generic/build: line 284: cd: /home/ilia/temp/openvpn-build/windows-nsis/tmp/build-i686/openvpn-2.3_git: No such file or directory
FATAL: cd openvpn
FATAL: build i686 >&2
FATAL: build-complete >&2
[ilia@localhost windows-nsis]$ 
```

**Comment by mattock** [comment]
Good catch. The default for OPENVPN_VERSION in build-snapshot was hardcoded to "2.3_git", which worked until openvpn-2.3_alpha2 was released. [This PR](https://github.com/OpenVPN/openvpn-build/pull/40) fixes it according to my tests. If you can, please test the fix yourself and approve the PR so that I can merge it.
