### ISSUE TITLE
*nix compilation with 2.4.3

### ISSUE THREAD

**Issue by Clodo76** [OpenVPN/openvpn-build#95]
First little issue: the OPENVPN_VERSION in current generic/build.vars contain '2.4.3',
but the relative file it's not yet here: http://build.openvpn.net/downloads/snapshots/ .
Resolved by using directly https://swupdate.openvpn.org/community/releases/openvpn-2.4.3.tar.gz

Second issue: under Linux Debian 7 (both 32bit and 64bit) and under macOS Sierra 10.12.5 throw a
ld: unrecognized option '--dynamicbase'.

Third issue (optional): here: https://openvpn.net/index.php/open-source/downloads.html
say "support for building with OpenSSL 1.1."
but still throw 'Unsupported options: no-multilib'.

Thx for any feedback.

**Comment by mattock** [comment]
Hi and thanks for reporting these!

1. I fixed this problem and added automation so that it should not happen again
1. You can fix this by simply commenting out or emptying EXTRA_TARGET_CFLAGS. This should produce a build that is functionally equal to what you had previously. We typically target our own slightly patched version of mingw-w64 that is based on packages from Ubuntu 14.04.
1. I'm not sure where this comes from. It could be that the new OpenSSL 1.1 support patchset included in OpenVPN 2.4.3 fails to compile properly with mingw-w64. Or it could be a local issue (i.e. too old mingw-w64 version) at your end. I notified the developer mailing list about this issue - hopefully someone joins this discussion.

**Comment by chipitsine** [comment]
for the second issue - the check of mingw-gcc today sucks. some systems are shipped with 4.8, however, you cannot build openvpn with 4.8, I think the same for --dynamicbase

we definetely need to improve mingw-gcc version check ))

I'll look at "3)" in few days (openssl-1.1.0 and openssl-1.0.2 should be built in slightly different ways)

**Comment by Clodo76** [comment]
For your knowledge,
Under Debian 7 (linux build) and macOS 10.12.5 (macOS build) i resolved with commenting EXTRA_TARGET_CFLAGS.
Under Debian 9 i compiled Windows edition with mingw-w64 without any issue, without touch EXTRA_TARGET_CFLAGS.
Thanks for your advice.

**Comment by chipitsine** [comment]
well, I got openssl cross builds for both 1.0.2 and 1.1.0, however, pkcs11-helper-1.11 is not ready yet for openssl-1.1.0, have a look

https://api.travis-ci.org/jobs/249719089/log.txt?deansi=true

**Comment by chipitsine** [comment]
as for Debian 7, I've made some investigation (you can run Debian 7 on https://dply.co for 2 hours):

```
forward.c: In function ‘process_outgoing_link’:
forward.c:1432:25: error: ‘ENETUNREACH’ undeclared (first use in this function)
forward.c:1432:25: note: each undeclared identifier is reported only once for each function it appears in
mv -f .deps/gremlin.Tpo .deps/gremlin.Po
i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -I../../include  -I../../include -I../../src/compat -DWIN32_LEAN_AND_MEAN -DNTDDI_VERSION=NTDDI_VISTA -D_WIN32_WINNT=_WIN32_WINNT_VISTA -I/root/openvpn-build/generic/image-win32/openvpn/include -I/root/openvpn-build/generic/image-win32/openvpn/include -I/root/openvpn-build/generic/image-win32/openvpn/include  -I/root/openvpn-build/generic/image-win32/openvpn/include -DPLUGIN_LIBDIR=\"//lib/openvpn/plugins\" -municode -UUNICODE -Wl,--dynamicbase,--nxcompat -std=c99 -MT httpdigest.o -MD -MP -MF .deps/httpdigest.Tpo -c -o httpdigest.o httpdigest.c
make[4]: *** [forward.o] Error 1
make[4]: *** Waiting for unfinished jobs....
```

it seems, mingw-4.6.3 is too old.
I'll try to make PR on that soon
